/**
 * The product catalog — everything the scanner knows how to price.
 *
 * Each product carries per-source search queries because retailers index
 * products inconsistently. The default query falls back to the product name.
 *
 * `queries` keys map to source ids in sources/. A missing key means "use the
 * product name as the search query for that source."
 *
 * For Apple products, the `appleChip` field helps the Apple Store source match
 * embedded chip-keyed prices (e.g. "m3ultra-28-60"). Discontinued chips (M1/M2
 * Max, M1/M2 Ultra) won't appear on the new store — they're refurb-only.
 */
import type { Product } from "./types.js";

export interface AppleProduct extends Product {
  /** Chip family for Apple Store matching, e.g. "m3ultra", "m4max". */
  appleChip?: string;
  /** Which Apple buy page this product lives on. */
  applePage?: "mac-studio" | "macbook-pro" | "mac-mini";
}

export const PRODUCTS: AppleProduct[] = [
  // ── NVIDIA GPUs — RTX 50 series ────────────────────────────────────────
  {
    id: "rtx-5090",
    name: "RTX 5090",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 5090", amazon: "RTX 5090", alternate: "RTX 5090" },
    minPriceUsd: 1500,
  },
  {
    id: "rtx-5080",
    name: "RTX 5080",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 5080", amazon: "RTX 5080", alternate: "RTX 5080" },
    minPriceUsd: 900,
  },
  {
    id: "rtx-5070-ti",
    name: "RTX 5070 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 5070 Ti", amazon: "RTX 5070 Ti", alternate: "RTX 5070 Ti" },
    minPriceUsd: 600,
  },
  {
    id: "rtx-5070",
    name: "RTX 5070",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 5070", amazon: "RTX 5070", alternate: "RTX 5070" },
    minPriceUsd: 500,
  },
  {
    id: "rtx-5060-ti",
    name: "RTX 5060 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 5060 Ti",
      amazon: "RTX 5060 Ti",
      alternate: "RTX 5060 Ti",
      ceneo: "RTX 5060 Ti",
      "awd-it": "RTX 5060 Ti",
      dospara: "RTX 5060 Ti",
    },
    minPriceUsd: 380,
  },
  {
    id: "rtx-5060",
    name: "RTX 5060",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 5060",
      amazon: "RTX 5060",
      alternate: "RTX 5060",
      ceneo: "RTX 5060",
      "awd-it": "RTX 5060",
      dospara: "RTX 5060",
    },
    minPriceUsd: 300,
  },

  // ── NVIDIA GPUs — RTX 40 series ────────────────────────────────────────
  {
    id: "rtx-4090",
    name: "RTX 4090",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4090", amazon: "RTX 4090", alternate: "RTX 4090" },
    minPriceUsd: 1200,
  },
  {
    id: "rtx-4080-super",
    name: "RTX 4080 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4080 Super", amazon: "RTX 4080 Super", alternate: "RTX 4080 Super" },
    minPriceUsd: 800,
  },
  {
    id: "rtx-4080",
    name: "RTX 4080",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4080", amazon: "RTX 4080", alternate: "RTX 4080" },
    minPriceUsd: 800,
  },
  {
    id: "rtx-4070-ti-super",
    name: "RTX 4070 Ti Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4070 Ti Super", amazon: "RTX 4070 Ti Super", alternate: "RTX 4070 Ti Super" },
    minPriceUsd: 700,
  },
  {
    id: "rtx-4070-ti",
    name: "RTX 4070 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4070 Ti", amazon: "RTX 4070 Ti", alternate: "RTX 4070 Ti" },
    minPriceUsd: 600,
  },
  {
    id: "rtx-4070-super",
    name: "RTX 4070 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4070 Super", amazon: "RTX 4070 Super", alternate: "RTX 4070 Super" },
    minPriceUsd: 500,
  },
  {
    id: "rtx-4070",
    name: "RTX 4070",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4070", amazon: "RTX 4070", alternate: "RTX 4070" },
    minPriceUsd: 450,
  },
  {
    id: "rtx-4060-ti",
    name: "RTX 4060 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4060 Ti", amazon: "RTX 4060 Ti", alternate: "RTX 4060 Ti" },
    minPriceUsd: 300,
  },
  {
    id: "rtx-4060",
    name: "RTX 4060",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 4060", amazon: "RTX 4060", alternate: "RTX 4060" },
    minPriceUsd: 250,
  },

  // ── NVIDIA GPUs — RTX 30 series ────────────────────────────────────────
  {
    id: "rtx-3090",
    name: "RTX 3090",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3090", amazon: "RTX 3090", alternate: "RTX 3090" },
    minPriceUsd: 600,
  },
  {
    id: "rtx-3080",
    name: "RTX 3080",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3080", amazon: "RTX 3080", alternate: "RTX 3080" },
    minPriceUsd: 400,
  },
  {
    id: "rtx-3070",
    name: "RTX 3070",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3070", amazon: "RTX 3070", alternate: "RTX 3070" },
    minPriceUsd: 300,
  },
  {
    id: "rtx-3060",
    name: "RTX 3060",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3060", amazon: "RTX 3060", alternate: "RTX 3060" },
    minPriceUsd: 200,
  },
  {
    id: "rtx-3060-ti",
    name: "RTX 3060 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3060 Ti", amazon: "RTX 3060 Ti", alternate: "RTX 3060 Ti", ceneo: "RTX 3060 Ti" },
    minPriceUsd: 220,
  },
  {
    id: "rtx-3070-ti",
    name: "RTX 3070 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3070 Ti", amazon: "RTX 3070 Ti", alternate: "RTX 3070 Ti", ceneo: "RTX 3070 Ti" },
    minPriceUsd: 280,
  },
  {
    id: "rtx-3080-ti",
    name: "RTX 3080 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 3080 Ti", amazon: "RTX 3080 Ti", alternate: "RTX 3080 Ti", ceneo: "RTX 3080 Ti" },
    minPriceUsd: 350,
  },

  // ── NVIDIA GPUs — workstation / DGX ────────────────────────────────────
  {
    id: "rtx-pro-6000-blackwell",
    name: "RTX Pro 6000 Blackwell",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX Pro 6000 Blackwell",
      amazon: "RTX Pro 6000 Blackwell",
      alternate: "RTX PRO 6000 Blackwell",
      ceneo: "RTX PRO 6000 Blackwell",
      dospara: "RTX PRO 6000 Blackwell",
    },
    minPriceUsd: 4000,
  },
  {
    id: "rtx-pro-4500-blackwell",
    name: "RTX Pro 4500 Blackwell",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX Pro 4500 Blackwell",
      amazon: "RTX Pro 4500 Blackwell",
      alternate: "RTX PRO 4500 Blackwell",
      ceneo: "RTX PRO 4500 Blackwell",
      dospara: "RTX PRO 4500 Blackwell",
    },
    minPriceUsd: 3500,
  },
  {
    id: "rtx-pro-4000-blackwell",
    name: "RTX Pro 4000 Blackwell",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX Pro 4000 Blackwell",
      amazon: "RTX Pro 4000 Blackwell",
      alternate: "RTX PRO 4000 Blackwell",
      ceneo: "RTX PRO 4000 Blackwell",
      dospara: "RTX PRO 4000 Blackwell",
    },
    minPriceUsd: 2000,
  },
  {
    id: "rtx-6000-ada",
    name: "RTX 6000 Ada",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX 6000 Ada", amazon: "RTX 6000 Ada", ceneo: "RTX 6000 Ada" },
    minPriceUsd: 4000,
  },
  {
    id: "rtx-4000-ada",
    name: "RTX 4000 Ada",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 4000 Ada",
      amazon: "RTX 4000 Ada",
      alternate: "RTX 4000 Ada",
      ceneo: "RTX 4000 Ada",
    },
    minPriceUsd: 1000,
  },
  {
    id: "rtx-2000-ada",
    name: "RTX 2000 Ada",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 2000 Ada",
      amazon: "RTX 2000 Ada",
      alternate: "RTX 2000 Ada",
      ceneo: "RTX 2000 Ada",
      dospara: "RTX 2000 Ada",
    },
    minPriceUsd: 500,
  },
  {
    id: "rtx-a6000",
    name: "RTX A6000",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "RTX A6000", amazon: "RTX A6000", alternate: "RTX A6000" },
    minPriceUsd: 3000,
  },
  {
    id: "dgx-spark",
    name: "NVIDIA DGX Spark",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: { newegg: "DGX Spark", amazon: "NVIDIA DGX Spark" },
    minPriceUsd: 3000,
  },

  // ── NVIDIA GPUs — datacenter (Hopper / Blackwell) ───────────────────────
  // These reach buyers through channel partners rather than a vendor list price,
  // but Newegg, Amazon and eBay all carry them, so they are priceable.
  {
    id: "h100",
    name: "H100",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "H100 80GB",
      amazon: "NVIDIA H100 80GB",
      ebay: "NVIDIA H100 80GB PCIe",
      ceneo: "NVIDIA H100",
    },
    minPriceUsd: 25000,
  },
  {
    id: "h200",
    name: "H200",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "H200 141GB",
      amazon: "NVIDIA H200 141GB",
      ebay: "NVIDIA H200 141GB",
      ceneo: "NVIDIA H200",
    },
    minPriceUsd: 30000,
  },
  {
    id: "a100",
    name: "A100",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "A100 80GB",
      amazon: "NVIDIA A100 80GB",
      ebay: "NVIDIA A100 80GB",
      ceneo: "NVIDIA A100",
    },
    minPriceUsd: 10000,
  },
  {
    id: "l40s",
    name: "L40S",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "L40S 48GB",
      amazon: "NVIDIA L40S 48GB",
      ebay: "NVIDIA L40S 48GB",
      ceneo: "NVIDIA L40S",
    },
    minPriceUsd: 7000,
  },
  {
    id: "rtx-pro-5000-blackwell",
    name: "RTX PRO 5000 Blackwell",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX PRO 5000 Blackwell",
      amazon: "RTX PRO 5000 Blackwell 48GB",
      ebay: "RTX PRO 5000 Blackwell",
      ceneo: "RTX PRO 5000 Blackwell",
    },
    minPriceUsd: 4200,
  },
  {
    id: "gb200",
    name: "GB200",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA GB200",
      ebay: "NVIDIA GB200 NVL72",
    },
    minPriceUsd: 60000,
  },
  {
    id: "mi325x",
    name: "Instinct MI325X",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      amazon: "AMD Instinct MI325X",
      ebay: "AMD Instinct MI325X 256GB",
    },
    minPriceUsd: 15000,
  },
  {
    id: "gaudi-3",
    name: "Gaudi 3",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      amazon: "Intel Gaudi 3",
      ebay: "Intel Gaudi 3 HL-338",
    },
    minPriceUsd: 16000,
  },

  {
    id: "b300",
    name: "B300",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA B300",
      ebay: "NVIDIA B300 Blackwell Ultra",
      ceneo: "NVIDIA B300",
    },
    minPriceUsd: 40000,
  },
  {
    id: "mi355x",
    name: "Instinct MI355X",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      amazon: "AMD Instinct MI355X",
      ebay: "AMD Instinct MI355X 288GB",
    },
    minPriceUsd: 25000,
  },
  {
    id: "l4",
    name: "L4",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "NVIDIA L4 24GB",
      amazon: "NVIDIA L4 24GB",
      ebay: "NVIDIA L4 24GB",
      ceneo: "NVIDIA L4",
    },
    minPriceUsd: 2000,
  },
  {
    id: "t4",
    name: "T4",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "NVIDIA T4 16GB",
      amazon: "NVIDIA T4 16GB",
      ebay: "NVIDIA T4 16GB",
      ceneo: "NVIDIA T4",
    },
    minPriceUsd: 500,
  },
  {
    id: "arc-pro-b50",
    name: "Intel Arc Pro B50",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc Pro B50",
      amazon: "Intel Arc Pro B50",
      alternate: "Arc Pro B50",
      ceneo: "Arc Pro B50",
      "awd-it": "Arc Pro B50",
    },
    minPriceUsd: 349,
  },
  {
    id: "rx-9070-gre",
    name: "Radeon RX 9070 GRE",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9070 GRE",
      amazon: "RX 9070 GRE",
      alternate: "RX 9070 GRE",
      ceneo: "RX 9070 GRE",
      "awd-it": "RX 9070 GRE",
    },
    minPriceUsd: 549,
  },

  {
    id: "rtx-a5000",
    name: "RTX A5000",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX A5000",
      amazon: "NVIDIA RTX A5000",
      ebay: "NVIDIA RTX A5000 24GB",
      ceneo: "RTX A5000",
    },
    minPriceUsd: 2250,
  },
  {
    id: "rtx-a4000",
    name: "RTX A4000",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX A4000",
      amazon: "NVIDIA RTX A4000",
      ebay: "NVIDIA RTX A4000 16GB",
      ceneo: "RTX A4000",
    },
    minPriceUsd: 1000,
  },
  {
    id: "rtx-5000-ada",
    name: "RTX 5000 Ada Generation",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 5000 Ada",
      amazon: "NVIDIA RTX 5000 Ada 32GB",
      ebay: "NVIDIA RTX 5000 Ada 32GB",
      ceneo: "RTX 5000 Ada",
    },
    minPriceUsd: 4000,
  },
  {
    id: "l40",
    name: "L40",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA L40 48GB",
      ebay: "NVIDIA L40 48GB",
      ceneo: "NVIDIA L40",
    },
    minPriceUsd: 5000,
  },
  {
    id: "v100",
    name: "Tesla V100",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Tesla V100 32GB",
      ebay: "NVIDIA Tesla V100 32GB",
      ceneo: "NVIDIA Tesla V100",
    },
    minPriceUsd: 800,
  },
  {
    id: "arc-a750",
    name: "Intel Arc A750",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc A750",
      amazon: "Intel Arc A750",
      alternate: "Arc A750",
      ceneo: "Arc A750",
      "awd-it": "Arc A750",
    },
    minPriceUsd: 289,
  },
  {
    id: "arc-a380",
    name: "Intel Arc A380",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc A380",
      amazon: "Intel Arc A380",
      alternate: "Arc A380",
      ceneo: "Arc A380",
      "awd-it": "Arc A380",
    },
    minPriceUsd: 139,
  },
  {
    id: "rx-9060-xt-8gb",
    name: "Radeon RX 9060 XT 8GB",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9060 XT 8GB",
      amazon: "RX 9060 XT 8GB",
      alternate: "RX 9060 XT 8GB",
      ceneo: "RX 9060 XT 8GB",
      "awd-it": "RX 9060 XT 8GB",
    },
    minPriceUsd: 299,
  },
  {
    id: "jetson-orin-nano",
    name: "Jetson Orin Nano Developer Kit",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Jetson Orin Nano Super Developer Kit",
      newegg: "Jetson Orin Nano",
      ebay: "Jetson Orin Nano Developer Kit",
      ceneo: "Jetson Orin Nano",
    },
    minPriceUsd: 249,
  },

  {
    id: "rtx-a2000",
    name: "RTX A2000",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX A2000",
      amazon: "NVIDIA RTX A2000 12GB",
      ebay: "NVIDIA RTX A2000 12GB",
      ceneo: "RTX A2000",
    },
    minPriceUsd: 450,
  },
  {
    id: "rtx-a4500",
    name: "RTX A4500",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA RTX A4500 20GB",
      ebay: "NVIDIA RTX A4500 20GB",
      ceneo: "RTX A4500",
    },
    minPriceUsd: 700,
  },
  {
    id: "rtx-a5500",
    name: "RTX A5500",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA RTX A5500 24GB",
      ebay: "NVIDIA RTX A5500 24GB",
      ceneo: "RTX A5500",
    },
    minPriceUsd: 4000,
  },
  {
    id: "arc-a580",
    name: "Intel Arc A580",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc A580",
      amazon: "Intel Arc A580",
      alternate: "Arc A580",
      ceneo: "Arc A580",
      "awd-it": "Arc A580",
    },
    minPriceUsd: 179,
  },
  {
    id: "arc-pro-a60",
    name: "Intel Arc Pro A60",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc Pro A60",
      amazon: "Intel Arc Pro A60 12GB",
      alternate: "Arc Pro A60",
      ceneo: "Arc Pro A60",
      "awd-it": "Arc Pro A60",
    },
    minPriceUsd: 175,
  },
  {
    id: "rx-9060",
    name: "Radeon RX 9060",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9060",
      amazon: "RX 9060",
      alternate: "RX 9060",
      ceneo: "RX 9060",
      "awd-it": "RX 9060",
    },
    minPriceUsd: 249,
  },
  {
    id: "rx-7900-gre",
    name: "Radeon RX 7900 GRE",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7900 GRE",
      amazon: "RX 7900 GRE",
      alternate: "RX 7900 GRE",
      ceneo: "RX 7900 GRE",
      "awd-it": "RX 7900 GRE",
    },
    minPriceUsd: 649,
  },
  {
    id: "radeon-pro-w7900",
    name: "Radeon Pro W7900",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon Pro W7900",
      amazon: "Radeon Pro W7900 48GB",
      ebay: "Radeon Pro W7900",
      ceneo: "Radeon Pro W7900",
    },
    minPriceUsd: 3999,
  },
  {
    id: "radeon-pro-w7800",
    name: "Radeon Pro W7800",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon Pro W7800",
      amazon: "Radeon Pro W7800 32GB",
      ebay: "Radeon Pro W7800",
      ceneo: "Radeon Pro W7800",
    },
    minPriceUsd: 2499,
  },
  {
    id: "jetson-orin-nx",
    name: "Jetson Orin NX Developer Kit",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "Jetson Orin NX 16GB Developer Kit",
      newegg: "Jetson Orin NX",
      ebay: "Jetson Orin NX 16GB",
      ceneo: "Jetson Orin NX",
    },
    minPriceUsd: 599,
  },

  {
    id: "rx-7800-xt",
    name: "Radeon RX 7800 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7800 XT",
      amazon: "RX 7800 XT",
      alternate: "RX 7800 XT",
      ceneo: "RX 7800 XT",
      "awd-it": "RX 7800 XT",
    },
    minPriceUsd: 499,
  },
  {
    id: "rx-7600",
    name: "Radeon RX 7600",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7600",
      amazon: "RX 7600",
      alternate: "RX 7600",
      ceneo: "RX 7600",
      "awd-it": "RX 7600",
    },
    minPriceUsd: 269,
  },
  {
    id: "rtx-2080-ti",
    name: "GeForce RTX 2080 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 2080 Ti",
      amazon: "RTX 2080 Ti",
      ebay: "RTX 2080 Ti 11GB",
      ceneo: "RTX 2080 Ti",
    },
    minPriceUsd: 999,
  },
  {
    id: "radeon-pro-w6800",
    name: "Radeon Pro W6800",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon Pro W6800",
      amazon: "Radeon Pro W6800 32GB",
      ebay: "Radeon Pro W6800",
      ceneo: "Radeon Pro W6800",
    },
    minPriceUsd: 2249,
  },
  {
    id: "jetson-agx-xavier",
    name: "Jetson AGX Xavier Developer Kit",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Jetson AGX Xavier Developer Kit 32GB",
      ebay: "Jetson AGX Xavier Developer Kit",
      ceneo: "Jetson AGX Xavier",
    },
    minPriceUsd: 1299,
  },
  {
    id: "arc-a310",
    name: "Intel Arc A310",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc A310",
      amazon: "Intel Arc A310 4GB",
      alternate: "Arc A310",
      ceneo: "Arc A310",
      "awd-it": "Arc A310",
    },
    minPriceUsd: 99,
  },
  {
    id: "mi250x",
    name: "Instinct MI250X",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      amazon: "AMD Instinct MI250X",
      ebay: "AMD Instinct MI250X 128GB",
    },
    minPriceUsd: 3000,
  },
  {
    id: "mi210",
    name: "Instinct MI210",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon Instinct MI210",
      amazon: "AMD Instinct MI210 64GB",
      ebay: "AMD Instinct MI210 64GB",
    },
    minPriceUsd: 3000,
  },

  {
    id: "rtx-2080-super",
    name: "RTX 2080 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 2080 Super",
      amazon: "RTX 2080 Super",
      ebay: "RTX 2080 Super",
      ceneo: "RTX 2080 Super",
    },
    minPriceUsd: 699,
  },
  {
    id: "rtx-2070-super",
    name: "RTX 2070 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 2070 Super",
      amazon: "RTX 2070 Super",
      ebay: "RTX 2070 Super",
      ceneo: "RTX 2070 Super",
    },
    minPriceUsd: 499,
  },
  {
    id: "rtx-2060-super",
    name: "RTX 2060 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "RTX 2060 Super",
      amazon: "RTX 2060 Super",
      ebay: "RTX 2060 Super",
      ceneo: "RTX 2060 Super",
    },
    minPriceUsd: 399,
  },
  {
    id: "gtx-1660-super",
    name: "GTX 1660 Super",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "GTX 1660 Super",
      amazon: "GTX 1660 Super",
      ebay: "GTX 1660 Super",
      ceneo: "GTX 1660 Super",
    },
    minPriceUsd: 229,
  },
  {
    id: "gtx-1080-ti",
    name: "GTX 1080 Ti",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "GTX 1080 Ti",
      amazon: "GTX 1080 Ti",
      ebay: "GTX 1080 Ti",
      ceneo: "GTX 1080 Ti",
    },
    minPriceUsd: 699,
  },
  {
    id: "rx-6800-xt",
    name: "Radeon RX 6800 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 6800 XT",
      amazon: "RX 6800 XT",
      alternate: "RX 6800 XT",
      ceneo: "RX 6800 XT",
      "awd-it": "RX 6800 XT",
    },
    minPriceUsd: 649,
  },
  {
    id: "rx-6700-xt",
    name: "Radeon RX 6700 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 6700 XT",
      amazon: "RX 6700 XT",
      alternate: "RX 6700 XT",
      ceneo: "RX 6700 XT",
      "awd-it": "RX 6700 XT",
    },
    minPriceUsd: 479,
  },
  {
    id: "rx-6600-xt",
    name: "Radeon RX 6600 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 6600 XT",
      amazon: "RX 6600 XT",
      alternate: "RX 6600 XT",
      ceneo: "RX 6600 XT",
      "awd-it": "RX 6600 XT",
    },
    minPriceUsd: 379,
  },

  {
    id: "gtx-1080",
    name: "GTX 1080",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "GTX 1080",
      amazon: "GTX 1080",
      ebay: "GTX 1080 8GB",
      ceneo: "GTX 1080",
    },
    minPriceUsd: 599,
  },
  {
    id: "gtx-1070",
    name: "GTX 1070",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "GTX 1070",
      amazon: "GTX 1070",
      ebay: "GTX 1070 8GB",
      ceneo: "GTX 1070",
    },
    minPriceUsd: 379,
  },
  {
    id: "gtx-1060",
    name: "GTX 1060",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      newegg: "GTX 1060",
      amazon: "GTX 1060",
      ebay: "GTX 1060 6GB",
      ceneo: "GTX 1060",
    },
    minPriceUsd: 249,
  },
  {
    id: "titan-v",
    name: "Titan V",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Titan V",
      ebay: "NVIDIA Titan V 12GB",
      ceneo: "Titan V",
    },
    minPriceUsd: 2999,
  },
  {
    id: "rx-6600",
    name: "Radeon RX 6600",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 6600",
      amazon: "RX 6600",
      alternate: "RX 6600",
      ceneo: "RX 6600",
      "awd-it": "RX 6600",
    },
    minPriceUsd: 329,
  },
  {
    id: "rx-6500-xt",
    name: "Radeon RX 6500 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 6500 XT",
      amazon: "RX 6500 XT",
      alternate: "RX 6500 XT",
      ceneo: "RX 6500 XT",
      "awd-it": "RX 6500 XT",
    },
    minPriceUsd: 199,
  },
  {
    id: "rx-5700-xt",
    name: "Radeon RX 5700 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 5700 XT",
      amazon: "RX 5700 XT",
      alternate: "RX 5700 XT",
      ceneo: "RX 5700 XT",
      "awd-it": "RX 5700 XT",
    },
    minPriceUsd: 399,
  },
  {
    id: "radeon-vii",
    name: "Radeon VII",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon VII",
      amazon: "Radeon VII 16GB",
      ebay: "Radeon VII 16GB",
      ceneo: "Radeon VII",
    },
    minPriceUsd: 699,
  },

  // ── NVIDIA — Jetson embedded ────────────────────────────────────────────
  {
    id: "jetson-agx-thor",
    name: "Jetson AGX Thor Developer Kit",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Jetson AGX Thor Developer Kit",
      newegg: "Jetson AGX Thor",
      ebay: "Jetson AGX Thor Developer Kit",
      ceneo: "Jetson AGX Thor",
    },
    minPriceUsd: 3499,
  },
  {
    id: "jetson-orin-agx",
    name: "Jetson AGX Orin Developer Kit",
    category: "gpu",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "NVIDIA Jetson AGX Orin 64GB",
      newegg: "Jetson AGX Orin",
      ebay: "Jetson AGX Orin 64GB",
      ceneo: "Jetson AGX Orin",
    },
    minPriceUsd: 1999,
  },

  // ── AMD GPUs — Radeon / Instinct ───────────────────────────────────────
  {
    id: "rx-9070-xt",
    name: "Radeon RX 9070 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9070 XT",
      amazon: "RX 9070 XT",
      alternate: "RX 9070 XT",
      ceneo: "RX 9070 XT",
      "awd-it": "RX 9070 XT",
    },
    minPriceUsd: 550,
  },
  {
    id: "rx-9070",
    name: "Radeon RX 9070",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9070",
      amazon: "RX 9070",
      alternate: "RX 9070",
      ceneo: "RX 9070",
      "awd-it": "RX 9070",
    },
    minPriceUsd: 549,
  },
  {
    id: "rx-9060-xt",
    name: "Radeon RX 9060 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 9060 XT 16GB",
      amazon: "RX 9060 XT 16GB",
      alternate: "RX 9060 XT",
      ceneo: "RX 9060 XT",
      "awd-it": "RX 9060 XT",
    },
    minPriceUsd: 349,
  },
  {
    id: "rx-7900-xtx",
    name: "Radeon RX 7900 XTX",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7900 XTX",
      amazon: "RX 7900 XTX",
      alternate: "RX 7900 XTX",
      ceneo: "RX 7900 XTX",
      "awd-it": "RX 7900 XTX",
    },
    minPriceUsd: 700,
  },
  {
    id: "rx-7900-xt",
    name: "Radeon RX 7900 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7900 XT",
      amazon: "RX 7900 XT",
      alternate: "RX 7900 XT",
      ceneo: "RX 7900 XT",
      "awd-it": "RX 7900 XT",
    },
    minPriceUsd: 600,
  },
  {
    id: "rx-7700-xt",
    name: "Radeon RX 7700 XT",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "RX 7700 XT",
      amazon: "RX 7700 XT",
      alternate: "RX 7700 XT",
      ceneo: "RX 7700 XT",
      "awd-it": "RX 7700 XT",
    },
    minPriceUsd: 350,
  },
  {
    id: "radeon-ai-pro-r9700",
    name: "Radeon AI PRO R9700",
    category: "gpu",
    manufacturer: "AMD",
    queries: {
      newegg: "Radeon AI PRO R9700",
      amazon: "Radeon AI PRO R9700",
      alternate: "Radeon AI PRO R9700",
      ceneo: "Radeon AI PRO R9700",
    },
    minPriceUsd: 1000,
  },

  // ── Intel GPUs — Arc Pro ────────────────────────────────────────────────
  {
    id: "intel-arc-pro-b60",
    name: "Intel Arc Pro B60",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc Pro B60",
      amazon: "Arc Pro B60",
      alternate: "Arc Pro B60",
      ceneo: "Arc Pro B60",
      "awd-it": "Arc Pro B60",
    },
    minPriceUsd: 450,
  },
  {
    id: "arc-b580",
    name: "Intel Arc B580",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc B580",
      amazon: "Intel Arc B580",
      alternate: "Arc B580",
      ceneo: "Arc B580",
      "awd-it": "Arc B580",
    },
    minPriceUsd: 249,
  },
  {
    id: "arc-b570",
    name: "Intel Arc B570",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc B570",
      amazon: "Intel Arc B570",
      alternate: "Arc B570",
      ceneo: "Arc B570",
      "awd-it": "Arc B570",
    },
    minPriceUsd: 219,
  },
  {
    id: "arc-a770",
    name: "Intel Arc A770",
    category: "gpu",
    manufacturer: "Intel",
    queries: {
      newegg: "Arc A770",
      amazon: "Intel Arc A770",
      alternate: "Arc A770",
      ceneo: "Arc A770",
      "awd-it": "Arc A770",
    },
    minPriceUsd: 349,
  },

  // ── Apple Silicon — Mac Studio ─────────────────────────────────────────
  // Current-gen (new store): M4 Max, M3 Ultra
  // Legacy (refurb/Amazon only): M1/M2 Max, M1/M2 Ultra
  {
    id: "mac-studio-m4-max",
    minPriceUsd: 1500,
    name: "Mac Studio M4 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m4max",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M4 Max" },
  },
  {
    id: "mac-studio-m3-ultra",
    minPriceUsd: 1500,
    name: "Mac Studio M3 Ultra",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m3ultra",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M3 Ultra" },
  },
  {
    id: "mac-studio-m1-max",
    minPriceUsd: 1500,
    name: "Mac Studio M1 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1max",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M1 Max" },
  },
  {
    id: "mac-studio-m2-max",
    minPriceUsd: 1500,
    name: "Mac Studio M2 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2max",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M2 Max" },
  },
  {
    id: "mac-studio-m1-ultra",
    minPriceUsd: 1500,
    name: "Mac Studio M1 Ultra",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1ultra",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M1 Ultra" },
  },
  {
    id: "mac-studio-m2-ultra",
    minPriceUsd: 1500,
    name: "Mac Studio M2 Ultra",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2ultra",
    applePage: "mac-studio",
    queries: { amazon: "Mac Studio M2 Ultra" },
  },

  // ── Apple Silicon — Mac mini ───────────────────────────────────────────
  // Current-gen (new store): M4, M4 Pro
  {
    id: "mac-mini-m4",
    minPriceUsd: 450,
    name: "Mac mini M4",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m4",
    applePage: "mac-mini",
    queries: { amazon: "Mac mini M4" },
  },
  {
    id: "mac-mini-m4-pro",
    minPriceUsd: 450,
    name: "Mac mini M4 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m4pro",
    applePage: "mac-mini",
    queries: { amazon: "Mac mini M4 Pro" },
  },
  {
    id: "mac-mini-m1",
    minPriceUsd: 450,
    name: "Mac mini M1",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1",
    applePage: "mac-mini",
    queries: { amazon: "Mac mini M1" },
  },
  {
    id: "mac-mini-m2",
    minPriceUsd: 450,
    name: "Mac mini M2",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2",
    applePage: "mac-mini",
    queries: { amazon: "Mac mini M2" },
  },
  {
    id: "mac-mini-m3",
    minPriceUsd: 450,
    name: "Mac mini M3",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m3",
    applePage: "mac-mini",
    queries: { amazon: "Mac mini M3" },
  },

  // ── Apple Silicon — MacBook Pro ────────────────────────────────────────
  // Current-gen (new store): M5, M5 Pro, M5 Max
  // Legacy (refurb/Amazon only): M1/M2/M3 Max
  {
    id: "macbook-pro-m5",
    minPriceUsd: 1200,
    name: "MacBook Pro M5",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m5",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M5" },
  },
  {
    id: "macbook-pro-m5-pro",
    minPriceUsd: 1200,
    name: "MacBook Pro M5 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m5pro",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M5 Pro" },
  },
  {
    id: "macbook-pro-m5-max",
    minPriceUsd: 1200,
    name: "MacBook Pro M5 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m5max",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M5 Max" },
  },
  {
    id: "macbook-pro-m4-pro",
    minPriceUsd: 1200,
    name: "MacBook Pro M4 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m4pro",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M4 Pro" },
  },
  {
    id: "macbook-pro-m4-max",
    minPriceUsd: 1200,
    name: "MacBook Pro M4 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m4max",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M4 Max" },
  },
  {
    id: "macbook-pro-m3-max",
    minPriceUsd: 1200,
    name: "MacBook Pro M3 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m3max",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M3 Max" },
  },
  {
    id: "macbook-pro-m2-max",
    minPriceUsd: 1200,
    name: "MacBook Pro M2 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2max",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M2 Max" },
  },
  {
    id: "macbook-pro-m1-max",
    minPriceUsd: 1200,
    name: "MacBook Pro M1 Max",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1max",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M1 Max" },
  },
  {
    id: "macbook-pro-m1",
    minPriceUsd: 1200,
    name: "MacBook Pro M1",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M1" },
  },
  {
    id: "macbook-pro-m1-pro",
    minPriceUsd: 1200,
    name: "MacBook Pro M1 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m1pro",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M1 Pro" },
  },
  {
    id: "macbook-pro-m2",
    minPriceUsd: 1200,
    name: "MacBook Pro M2",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M2" },
  },
  {
    id: "macbook-pro-m2-pro",
    minPriceUsd: 1200,
    name: "MacBook Pro M2 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m2pro",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M2 Pro" },
  },
  {
    id: "macbook-pro-m3",
    minPriceUsd: 1200,
    name: "MacBook Pro M3",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m3",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M3" },
  },
  {
    id: "macbook-pro-m3-pro",
    minPriceUsd: 1200,
    name: "MacBook Pro M3 Pro",
    category: "apple",
    manufacturer: "Apple",
    appleChip: "m3pro",
    applePage: "macbook-pro",
    queries: { amazon: "MacBook Pro M3 Pro" },
  },

  // ── AMD Strix Halo ─────────────────────────────────────────────────────
  {
    id: "amd-strix-halo-framework-desktop",
    minPriceUsd: 1000,
    name: "Framework Desktop (AMD Ryzen AI Max 395+)",
    category: "amd",
    manufacturer: "AMD / Framework",
    queries: { newegg: "Framework Desktop AMD Ryzen AI Max", amazon: "Framework Desktop Ryzen AI Max" },
  },
  {
    id: "amd-strix-halo-mini-pc",
    minPriceUsd: 1000,
    name: "Strix Halo Mini PC (Ryzen AI Max)",
    category: "amd",
    manufacturer: "AMD / Minisforum/GMKtec",
    queries: { newegg: "Ryzen AI Max mini PC", amazon: "Ryzen AI Max mini PC" },
  },

  // ── Memory ─────────────────────────────────────────────────────────────
  {
    id: "ddr5-32gb-5600",
    minPriceUsd: 60,
    name: "32GB DDR5-5600 (2×16GB)",
    category: "memory",
    manufacturer: "Various",
    queries: { newegg: "DDR5-5600 32GB", amazon: "DDR5-5600 32GB kit", alternate: "DDR5-5600 32GB" },
  },
  {
    id: "ddr5-64gb-5600",
    minPriceUsd: 120,
    name: "64GB DDR5-5600 (2×32GB)",
    category: "memory",
    manufacturer: "Various",
    queries: { newegg: "DDR5-5600 64GB", amazon: "DDR5-5600 64GB kit", alternate: "DDR5-5600 64GB" },
  },
  {
    id: "ddr4-32gb-3200",
    minPriceUsd: 50,
    name: "32GB DDR4-3200 (2×16GB)",
    category: "memory",
    manufacturer: "Various",
    queries: { newegg: "DDR4-3200 32GB", amazon: "DDR4-3200 32GB kit", alternate: "DDR4-3200 32GB" },
  },
  {
    id: "ddr4-ecc-64gb",
    minPriceUsd: 150,
    name: "64GB DDR4 ECC (Registered)",
    category: "memory",
    manufacturer: "Various",
    queries: { newegg: "DDR4 ECC 64GB registered", amazon: "DDR4 ECC 64GB RDIMM" },
  },
  {
    id: "ddr5-ecc-64gb",
    minPriceUsd: 200,
    name: "64GB DDR5 ECC (Registered)",
    category: "memory",
    manufacturer: "Various",
    queries: { newegg: "DDR5 ECC 64GB RDIMM", amazon: "DDR5 ECC 64GB RDIMM" },
  },

  // ── Laptops ────────────────────────────────────────────────────────────
  // Queries are keyed by source id: `amazon` (English), `morele` (Polish),
  // `alternate` (German market), `dospara` (Japanese market). Dell machines
  // use their service-tag model codes (DA16260 etc.) because vendor and
  // Dell-carrying retailers index by them. queryFor falls back to the product
  // name for any source without an explicit key.
  {
    id: "dell-xps-16-da16260",
    name: "Dell XPS 16 (DA16260, Core Ultra X7 358H, 3.2K OLED)",
    category: "laptop",
    manufacturer: "Dell",
    queries: {
      amazon: "Dell XPS 16",
      morele: "laptop Dell XPS 16 DA16260",
      alternate: "Dell XPS 16 Core Ultra 358H",
      dospara: "Dell XPS 16",
    },
    minPriceUsd: 2000,
  },
  {
    id: "dell-16-premium-da16250",
    name: "Dell 16 Premium (DA16250, RTX 5070 8GB, 4K OLED)",
    category: "laptop",
    manufacturer: "Dell",
    queries: {
      amazon: "Dell 16 Premium RTX 5070",
      morele: "laptop Dell 16 Premium DA16250",
      alternate: "Dell 16 Premium RTX 5070",
      dospara: "Dell 16 Premium",
    },
    minPriceUsd: 2400,
  },
  {
    id: "dell-xps-14-da14260",
    name: "Dell XPS 14 (DA14260)",
    category: "laptop",
    manufacturer: "Dell",
    queries: {
      amazon: "Dell XPS 14",
      morele: "laptop Dell XPS 14 DA14260",
      alternate: "Dell XPS 14 Core Ultra",
      dospara: "Dell XPS 14",
    },
    minPriceUsd: 1700,
  },
  {
    id: "dell-xps-13-dx13260",
    name: "Dell XPS 13 (DX13260)",
    category: "laptop",
    manufacturer: "Dell",
    queries: {
      amazon: "Dell XPS 13",
      morele: "laptop Dell XPS 13 DX13260",
      alternate: "Dell XPS 13 Core Ultra",
      dospara: "Dell XPS 13",
    },
    minPriceUsd: 1300,
  },
  {
    id: "macbook-pro-14-m5-pro",
    name: "MacBook Pro 14 (M5 Pro)",
    category: "laptop",
    manufacturer: "Apple",
    queries: {
      amazon: "MacBook Pro 14 M5 Pro",
      morele: "laptop Apple MacBook Pro 14 M5 Pro",
      alternate: "Apple MacBook Pro 14 M5 Pro",
      dospara: "MacBook Pro 14 M5",
    },
    minPriceUsd: 1999,
  },
  {
    id: "macbook-pro-16-m5-max",
    name: "MacBook Pro 16 (M5 Max)",
    category: "laptop",
    manufacturer: "Apple",
    queries: {
      amazon: "MacBook Pro 16 M5 Max",
      morele: "laptop Apple MacBook Pro 16 M5 Max",
      alternate: "Apple MacBook Pro 16 M5 Max",
      dospara: "MacBook Pro 16 M5",
    },
    minPriceUsd: 3499,
  },
  {
    id: "macbook-air-13-m5",
    name: "MacBook Air 13 (M5)",
    category: "laptop",
    manufacturer: "Apple",
    queries: {
      amazon: "MacBook Air 13 M5",
      morele: "laptop Apple MacBook Air 13 M5",
      alternate: "Apple MacBook Air 13 M5",
      dospara: "MacBook Air 13 M5",
    },
    minPriceUsd: 1099,
  },
  {
    id: "macbook-air-15-m5",
    name: "MacBook Air 15 (M5)",
    category: "laptop",
    manufacturer: "Apple",
    queries: {
      amazon: "MacBook Air 15 M5",
      morele: "laptop Apple MacBook Air 15 M5",
      alternate: "Apple MacBook Air 15 M5",
      dospara: "MacBook Air 15 M5",
    },
    minPriceUsd: 1299,
  },
  {
    id: "framework-13",
    name: "Framework Laptop 13",
    category: "laptop",
    manufacturer: "Framework",
    queries: {
      amazon: "Framework Laptop 13",
      morele: "laptop Framework 13",
      alternate: "Framework Laptop 13",
      dospara: "Framework Laptop 13",
    },
    minPriceUsd: 1000,
  },
  {
    id: "framework-16",
    name: "Framework Laptop 16",
    category: "laptop",
    manufacturer: "Framework",
    queries: {
      amazon: "Framework Laptop 16",
      morele: "laptop Framework 16",
      alternate: "Framework Laptop 16",
      dospara: "Framework Laptop 16",
    },
    minPriceUsd: 1600,
  },
  {
    id: "lenovo-thinkpad-x1-carbon-g12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    category: "laptop",
    manufacturer: "Lenovo",
    queries: {
      amazon: "Lenovo ThinkPad X1 Carbon Gen 12",
      morele: "laptop Lenovo ThinkPad X1 Carbon Gen 12",
      alternate: "Lenovo ThinkPad X1 Carbon G12",
      dospara: "ThinkPad X1 Carbon",
    },
    minPriceUsd: 1700,
  },
  {
    id: "asus-zenbook-14-oled",
    name: "ASUS Zenbook 14 OLED",
    category: "laptop",
    manufacturer: "ASUS",
    queries: {
      amazon: "ASUS Zenbook 14 OLED",
      morele: "laptop Asus Zenbook 14 OLED",
      alternate: "Asus Zenbook 14 OLED",
      dospara: "ASUS Zenbook 14 OLED",
    },
    minPriceUsd: 1000,
  },
  {
    id: "hp-omnibook-x-flip",
    name: "HP OmniBook X Flip",
    category: "laptop",
    manufacturer: "HP",
    queries: {
      amazon: "HP OmniBook X Flip",
      morele: "laptop HP OmniBook X Flip",
      alternate: "HP OmniBook X Flip",
      dospara: "HP OmniBook X Flip",
    },
    minPriceUsd: 1100,
  },
  {
    id: "razer-blade-16-rtx-5090",
    name: "Razer Blade 16 (RTX 5090 Laptop 24GB)",
    category: "laptop",
    manufacturer: "Razer",
    queries: {
      amazon: "Razer Blade 16 RTX 5090",
      morele: "laptop Razer Blade 16 RTX 5090",
      alternate: "Razer Blade 16 RTX 5090",
      dospara: "Razer Blade 16 RTX 5090",
    },
    minPriceUsd: 2000,
  },
  {
    id: "razer-blade-16-rtx-5080",
    name: "Razer Blade 16 (RTX 5080 Laptop 16GB)",
    category: "laptop",
    manufacturer: "Razer",
    queries: {
      amazon: "Razer Blade 16 RTX 5080",
      morele: "laptop Razer Blade 16 RTX 5080",
      alternate: "Razer Blade 16 RTX 5080",
      dospara: "Razer Blade 16 RTX 5080",
    },
    minPriceUsd: 1500,
  },

  // ── Laptop GPUs ────────────────────────────────────────────────────────
  // Sold as a configured machine, so the listing is the laptop rather than a
  // card; the query names the GPU because that is what buyers search for.
  {
    id: "rtx-5090-laptop",
    name: "RTX 5090 Laptop",
    category: "laptop",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "RTX 5090 laptop",
      morele: "laptop RTX 5090",
      alternate: "RTX 5090 Laptop",
      dospara: "RTX 5090 ノートPC",
    },
    minPriceUsd: 2500,
  },
  {
    id: "rtx-5080-laptop",
    name: "RTX 5080 Laptop",
    category: "laptop",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "RTX 5080 laptop",
      morele: "laptop RTX 5080",
      alternate: "RTX 5080 Laptop",
      dospara: "RTX 5080 ノートPC",
    },
    minPriceUsd: 2000,
  },
  {
    id: "rtx-4090-laptop",
    name: "RTX 4090 Laptop",
    category: "laptop",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "RTX 4090 laptop",
      morele: "laptop RTX 4090",
      alternate: "RTX 4090 Laptop",
      dospara: "RTX 4090 ノートPC",
    },
    minPriceUsd: 2000,
  },
  {
    id: "rtx-5070-ti-laptop",
    name: "RTX 5070 Ti Laptop",
    category: "laptop",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "RTX 5070 Ti laptop",
      morele: "laptop RTX 5070 Ti",
      alternate: "RTX 5070 Ti Laptop",
      dospara: "RTX 5070 Ti ノートPC",
    },
    minPriceUsd: 1500,
  },
  {
    id: "rtx-4060-laptop",
    name: "RTX 4060 Laptop",
    category: "laptop",
    manufacturer: "NVIDIA",
    queries: {
      amazon: "RTX 4060 laptop",
      morele: "laptop RTX 4060",
      alternate: "RTX 4060 Laptop",
      dospara: "RTX 4060 ノートPC",
    },
    minPriceUsd: 800,
  },
];

/** Find a product by id. */
export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

/** Products filtered by category. */
export function productsByCategory(category: Product["category"]): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

/** Apple products only (have appleChip/applePage). */
export function appleProducts(): AppleProduct[] {
  return PRODUCTS.filter((p) => p.appleChip && p.applePage);
}

/** Resolve the search query for a product on a given source (falls back to name). */
export function queryFor(product: Product, source: string): string {
  return product.queries[source] ?? product.name;
}
